In [2]:
import torch

In [4]:
x = torch.empty(1) # scalar
print(x)

x = torch.empty(3) # vector
print(x)

x = torch.empty(2, 3) # matrix
print(x)

x = torch.empty(2, 2, 3) # 3D tensor
print(x)

x = torch.rand(5, 3)
print(x)

x = torch.zeros(5, 3)
print(x)

x = torch.ones(5, 3)
print(x)

# check size
print(x.size())

print(x.dtype)

tensor([0.])
tensor([0.0000, 1.8750, 0.0000])
tensor([[-3.0314e+00,  9.9632e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[[-3.0470e+00,  9.9632e-43,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
tensor([[0.3710, 0.6302, 0.3466],
        [0.9654, 0.9089, 0.1348],
        [0.3275, 0.9063, 0.1241],
        [0.1894, 0.6988, 0.4798],
        [0.7693, 0.3859, 0.2265]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([5, 3])
torch.float32


In [5]:
x = torch.ones(5, 3, dtype=torch.int)
print(x.dtype)

torch.int32


In [6]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [7]:
x = torch.tensor([5.5, 3])
y = torch.tensor([3.5, 2])
print(x + y)
print(torch.add(x, y))

tensor([9., 5.])
tensor([9., 5.])


In [8]:
# slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) # all rows, first column
print(x[1, :]) # second row, all columns
print(x[1, 1]) # second row, second column

tensor([[0.2249, 0.4663, 0.7224],
        [0.0114, 0.5938, 0.7813],
        [0.3966, 0.9917, 0.0441],
        [0.2327, 0.2012, 0.5586],
        [0.9607, 0.3823, 0.7976]])
tensor([0.2249, 0.0114, 0.3966, 0.2327, 0.9607])
tensor([0.0114, 0.5938, 0.7813])
tensor(0.5938)


In [11]:
# reshape with view
x = torch.rand(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1 means infer from other dimensions
print(x.size(), y.size(), z.size())
print(x)
print(y)
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[0.1929, 0.5570, 0.0649, 0.3494],
        [0.6478, 0.1984, 0.5509, 0.3244],
        [0.8092, 0.4388, 0.2192, 0.3866],
        [0.0306, 0.9576, 0.5113, 0.7404]])
tensor([0.1929, 0.5570, 0.0649, 0.3494, 0.6478, 0.1984, 0.5509, 0.3244, 0.8092,
        0.4388, 0.2192, 0.3866, 0.0306, 0.9576, 0.5113, 0.7404])
tensor([[0.1929, 0.5570, 0.0649, 0.3494, 0.6478, 0.1984, 0.5509, 0.3244],
        [0.8092, 0.4388, 0.2192, 0.3866, 0.0306, 0.9576, 0.5113, 0.7404]])


In [12]:
# convert from numpy
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)



[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [13]:
# convert to numpy 
a= torch.ones(5)
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [ ]:
# both share memory
a += 1
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
# by default, tensors are created on CPU
# to create on GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) # create on GPU
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[1.1929, 1.5570, 1.0649, 1.3494],
        [1.6478, 1.1984, 1.5509, 1.3244],
        [1.8092, 1.4388, 1.2192, 1.3866],
        [1.0306, 1.9576, 1.5113, 1.7404]], device='cuda:0')
tensor([[1.1929, 1.5570, 1.0649, 1.3494],
        [1.6478, 1.1984, 1.5509, 1.3244],
        [1.8092, 1.4388, 1.2192, 1.3866],
        [1.0306, 1.9576, 1.5113, 1.7404]], dtype=torch.float64)


In [ ]:
# let torch know that we need to calculate gradients
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
